##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # influxdb
  influxdb:
    image: ${IMAGE_REPO}/${IMAGE_INFLUXDB}
    container_name: "influxdb.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "influxdb.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASS}
      #- INFLUXDB_DB=${INFLUXDB_DB}
      #- INFLUXDB_USER=${INFLUXDB_DB_ALL_USER}
      #- INFLUXDB_USER_PASSWORD=${INFLUXDB_DB_ALL_PASS}
      #- INFLUXDB_READ_USER=${INFLUXDB_DB_READ_USER}
      #- INFLUXDB_READ_USER_PASSWORD=${INFLUXDB_DB_READ_PASS}
      #- INFLUXDB_WRITE_USER=${INFLUXDB_DB_WRITE_USER}
      #- INFLUXDB_WRITE_USER_PASSWORD=${INFLUXDB_DB_WRITE_PASS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/influxdb/data:/var/lib/influxdb:rw
      - ./volume/influxdb/temp:/back:rw
    network_mode: "host"
  # chronograf
  chronograf:
    image: ${IMAGE_REPO}/${IMAGE_CHRONOGRAF}
    container_name: "chronograf.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "chronograf.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/chronograf/data:/var/lib/chronograf:rw
    command: --influxdb-url=http://127.0.0.1:8086 --influxdb-username=${INFLUXDB_ADMIN_USER} --influxdb-password=${INFLUXDB_ADMIN_PASS}
    network_mode: "host"
