##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # influxdb
  influxdb:
    image: ${IMAGE_REPO}/${IMAGE_INFLUXDB}
    container_name: "influxdb.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "influxdb.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    env_file:
      - ./influxdb.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./volume/influxdb/data:/var/lib/influxdb:rw
      - ./volume/influxdb/logs:/var/log/influxdb:rw
      - ./volume/influxdb/temp:/back:rw
    network_mode: "host"
  # chronograf
  chronograf:
    image: ${IMAGE_REPO}/${IMAGE_CHRONOGRAF}
    container_name: "chronograf.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "chronograf.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    env_file:
      - ./influxdb.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/chronograf/data:/var/lib/chronograf:rw
    network_mode: "host"
